services:
  - type: web
    name: kavya-portfolio
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:kgnyzssjevtcs@db.jgzdxkfkeuexvhnhckmj.supabase.co:5432/postgres?sslmode=require
      - key: SENDGRID_API_KEY
        value: your_sendgrid_api_key_here
      - key: SENDGRID_VERIFIED_SENDER
        value:  kavyasiddharthan07@gmail.com
